### ISSUE TITLE
Unable to locate iconik-storage-gateway

### ISSUE THREAD

**Issue by v-h-z** [iconik-io/iconik-storage-gateway-docker#2]
Hello!
looks like apt-get is unable to locate iconik-storage-gateway package?
Name changed or repo?

**Comment by odeshog** [comment]
are you building for arm arch? unfortunaly we only package for amd64 on Ubuntu

**Comment by v-h-z** [comment]
Oh no docker on apple silicon then
Thanks for the reply!

**Comment by MikaelWahlberg** [comment]
It is much better to run the ISG native Mac app on Apple Silicon anyways.
